//HintName: Priority.EFCore.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
internal sealed class PriorityValueConverter
    : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<global::Priority, int>
{
    public PriorityValueConverter()
        : base(static v => v.Value, static v => FromValue(v))
    { }

    private static global::Priority FromValue(int v) =>
        global::Priority.TryFromValue(v, out var result)
            ? result!
            : throw new global::System.InvalidOperationException(
                $"'{v}' is not a valid value for Priority.");
}

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
internal sealed class PriorityNameConverter
    : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<global::Priority, global::System.String>
{
    public PriorityNameConverter()
        : base(static v => v.Name, static v => FromName(v))
    { }

    private static global::Priority FromName(global::System.String v) =>
        global::Priority.TryFromName(v, out var result)
            ? result!
            : throw new global::System.InvalidOperationException(
                $"'{v}' is not a valid name for Priority.");
}

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
public static class PriorityEfCoreExtensions
{
    public static global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::Priority> HasPriorityConversionByValue(
        this global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::Priority> builder)
    {
        builder.HasConversion<global::PriorityValueConverter>();
        return builder;
    }

    public static global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::Priority> HasPriorityConversionByName(
        this global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::Priority> builder)
    {
        builder.HasConversion<global::PriorityNameConverter>();
        return builder;
    }
}
