//HintName: MyApp.Domain.OrderStatus.EFCore.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyApp.Domain;

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
internal sealed class OrderStatusValueConverter
    : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<global::MyApp.Domain.OrderStatus, int>
{
    public OrderStatusValueConverter()
        : base(static v => v.Value, static v => FromValue(v))
    { }

    private static global::MyApp.Domain.OrderStatus FromValue(int v) =>
        global::MyApp.Domain.OrderStatus.TryFromValue(v, out var result)
            ? result!
            : throw new global::System.InvalidOperationException(
                $"'{v}' is not a valid value for OrderStatus.");
}

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
internal sealed class OrderStatusNameConverter
    : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<global::MyApp.Domain.OrderStatus, global::System.String>
{
    public OrderStatusNameConverter()
        : base(static v => v.Name, static v => FromName(v))
    { }

    private static global::MyApp.Domain.OrderStatus FromName(global::System.String v) =>
        global::MyApp.Domain.OrderStatus.TryFromName(v, out var result)
            ? result!
            : throw new global::System.InvalidOperationException(
                $"'{v}' is not a valid name for OrderStatus.");
}

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
internal static class MyApp_Domain_OrderStatusEfCoreExtensions
{
    public static global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.OrderStatus> HasOrderStatusConversionByValue(
        this global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.OrderStatus> builder)
    {
        builder.HasConversion<global::MyApp.Domain.OrderStatusValueConverter>();
        return builder;
    }

    public static global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.OrderStatus> HasOrderStatusConversionByName(
        this global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.OrderStatus> builder)
    {
        builder.HasConversion<global::MyApp.Domain.OrderStatusNameConverter>();
        return builder;
    }
}
