//HintName: OptimizedEnumEfCoreAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace LayeredCraft.OptimizedEnums.EFCore
{
    /// <summary>
    /// Controls how an OptimizedEnum property is stored in the database.
    /// </summary>
    public enum OptimizedEnumEfCoreStorage
    {
        /// <summary>Store as the member's underlying Value (e.g. 1 for an int-valued enum).</summary>
        ByValue = 0,

        /// <summary>Store as the member's Name string (e.g. "Pending").</summary>
        ByName = 1,
    }

    /// <summary>
    /// Instructs the OptimizedEnums source generator to emit Entity Framework Core
    /// value converters and comparer for the decorated OptimizedEnum class.
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class,
        AllowMultiple = false,
        Inherited = false)]
    public sealed class OptimizedEnumEfCoreAttribute : global::System.Attribute
    {
        /// <summary>Initializes a new instance.</summary>
        public OptimizedEnumEfCoreAttribute(
            OptimizedEnumEfCoreStorage storage = OptimizedEnumEfCoreStorage.ByValue)
        {
            Storage = storage;
        }

        /// <summary>Gets the default storage mode for this enum.</summary>
        public OptimizedEnumEfCoreStorage Storage { get; }
    }
}