//HintName: OptimizedEnumEfCoreConventions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace LayeredCraft.OptimizedEnums.EFCore
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
    public static class OptimizedEnumEfCoreConventionExtensions
    {
        public static global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder ConfigureOptimizedEnums(
            this global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder builder)
        {
            
                        builder.Properties<global::Priority>()
                            .HaveConversion<global::PriorityValueConverter>();
                        
            return builder;
        }
    }
}
