//HintName: MyApp.Domain.Color.EFCore.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyApp.Domain;

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
internal sealed class ColorValueConverter
    : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<global::MyApp.Domain.Color, string>
{
    public ColorValueConverter()
        : base(static v => v.Value, static v => FromValue(v))
    { }

    private static global::MyApp.Domain.Color FromValue(string v) =>
        global::MyApp.Domain.Color.TryFromValue(v, out var result)
            ? result!
            : throw new global::System.InvalidOperationException(
                $"'{v}' is not a valid value for Color.");
}

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
internal sealed class ColorNameConverter
    : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<global::MyApp.Domain.Color, global::System.String>
{
    public ColorNameConverter()
        : base(static v => v.Name, static v => FromName(v))
    { }

    private static global::MyApp.Domain.Color FromName(global::System.String v) =>
        global::MyApp.Domain.Color.TryFromName(v, out var result)
            ? result!
            : throw new global::System.InvalidOperationException(
                $"'{v}' is not a valid name for Color.");
}

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
internal static class MyApp_Domain_ColorEfCoreExtensions
{
    public static global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.Color> HasColorConversionByValue(
        this global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.Color> builder)
    {
        builder.HasConversion<global::MyApp.Domain.ColorValueConverter>();
        return builder;
    }

    public static global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.Color> HasColorConversionByName(
        this global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.Color> builder)
    {
        builder.HasConversion<global::MyApp.Domain.ColorNameConverter>();
        return builder;
    }
}
