//HintName: MyApp.Domain.Outer.Status.EFCore.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyApp.Domain;

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
internal sealed class OuterStatusValueConverter
    : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<global::MyApp.Domain.Outer.Status, int>
{
    public OuterStatusValueConverter()
        : base(static v => v.Value, static v => FromValue(v))
    { }

    private static global::MyApp.Domain.Outer.Status FromValue(int v) =>
        global::MyApp.Domain.Outer.Status.TryFromValue(v, out var result)
            ? result!
            : throw new global::System.InvalidOperationException(
                $"'{v}' is not a valid value for Status.");
}

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
internal sealed class OuterStatusNameConverter
    : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<global::MyApp.Domain.Outer.Status, global::System.String>
{
    public OuterStatusNameConverter()
        : base(static v => v.Name, static v => FromName(v))
    { }

    private static global::MyApp.Domain.Outer.Status FromName(global::System.String v) =>
        global::MyApp.Domain.Outer.Status.TryFromName(v, out var result)
            ? result!
            : throw new global::System.InvalidOperationException(
                $"'{v}' is not a valid name for Status.");
}

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.EFCore.Generator", "REPLACED")]
public static class MyApp_Domain_Outer_StatusEfCoreExtensions
{
    public static global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.Outer.Status> HasStatusConversionByValue(
        this global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.Outer.Status> builder)
    {
        builder.HasConversion<global::MyApp.Domain.OuterStatusValueConverter>();
        return builder;
    }

    public static global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.Outer.Status> HasStatusConversionByName(
        this global::Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<global::MyApp.Domain.Outer.Status> builder)
    {
        builder.HasConversion<global::MyApp.Domain.OuterStatusNameConverter>();
        return builder;
    }
}
