//HintName: MyApp.Domain.Outer.Status.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyApp.Domain;

partial class Outer
{
[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
partial class Status
{
    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<global::MyApp.Domain.Outer.Status> s_all =
        global::System.Array.AsReadOnly(new global::MyApp.Domain.Outer.Status[]
        {
            Active,
            Inactive
        });

    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<string> s_names =
        global::System.Array.AsReadOnly(new string[]
        {
            Active.Name,
            Inactive.Name
        });

    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<int> s_values =
        global::System.Array.AsReadOnly(new int[]
        {
            Active.Value,
            Inactive.Value
        });

    private static readonly global::System.Collections.Generic.Dictionary<string, global::MyApp.Domain.Outer.Status> s_byName =
        new global::System.Collections.Generic.Dictionary<string, global::MyApp.Domain.Outer.Status>(2, global::System.StringComparer.Ordinal)
        {
            [Active.Name] = Active,
            [Inactive.Name] = Inactive
        };

    private static readonly global::System.Collections.Generic.Dictionary<int, global::MyApp.Domain.Outer.Status> s_byValue =
        new global::System.Collections.Generic.Dictionary<int, global::MyApp.Domain.Outer.Status>(2)
        {
            [Active.Value] = Active,
            [Inactive.Value] = Inactive
        };

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<global::MyApp.Domain.Outer.Status> All => s_all;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<string> Names => s_names;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<int> Values => s_values;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public const int Count = 2;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::MyApp.Domain.Outer.Status FromName(string name)
    {
        if (!s_byName.TryGetValue(name, out var result))
            throw new global::System.Collections.Generic.KeyNotFoundException(
                $"'{name}' is not a valid name for Status");

        return result;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool TryFromName(string name, out global::MyApp.Domain.Outer.Status? result) =>
        s_byName.TryGetValue(name, out result);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::MyApp.Domain.Outer.Status FromValue(int value)
    {
        if (!s_byValue.TryGetValue(value, out var result))
            throw new global::System.Collections.Generic.KeyNotFoundException(
                $"'{value}' is not a valid value for Status");

        return result;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool TryFromValue(int value, out global::MyApp.Domain.Outer.Status? result) =>
        s_byValue.TryGetValue(value, out result);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool ContainsName(string name) => s_byName.ContainsKey(name);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool ContainsValue(int value) => s_byValue.ContainsKey(value);
}
}
