//HintName: MyApp.Domain.DayOfWeek.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyApp.Domain;

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
partial class DayOfWeek
{
    private static readonly global::MyApp.Domain.DayOfWeek[] s_all = new global::MyApp.Domain.DayOfWeek[]
    {
        Monday,
        Tuesday,
        Wednesday,
        Thursday,
        Friday,
        Saturday,
        Sunday
    };

    private static readonly string[] s_names = new string[]
    {
        Monday.Name,
        Tuesday.Name,
        Wednesday.Name,
        Thursday.Name,
        Friday.Name,
        Saturday.Name,
        Sunday.Name
    };

    private static readonly int[] s_values = new int[]
    {
        Monday.Value,
        Tuesday.Value,
        Wednesday.Value,
        Thursday.Value,
        Friday.Value,
        Saturday.Value,
        Sunday.Value
    };

    private static readonly global::System.Collections.Generic.Dictionary<string, global::MyApp.Domain.DayOfWeek> s_byName =
        new global::System.Collections.Generic.Dictionary<string, global::MyApp.Domain.DayOfWeek>(global::System.StringComparer.Ordinal)
        {
            [Monday.Name] = Monday,
            [Tuesday.Name] = Tuesday,
            [Wednesday.Name] = Wednesday,
            [Thursday.Name] = Thursday,
            [Friday.Name] = Friday,
            [Saturday.Name] = Saturday,
            [Sunday.Name] = Sunday
        };

    private static readonly global::System.Collections.Generic.Dictionary<int, global::MyApp.Domain.DayOfWeek> s_byValue =
        new global::System.Collections.Generic.Dictionary<int, global::MyApp.Domain.DayOfWeek>()
        {
            [Monday.Value] = Monday,
            [Tuesday.Value] = Tuesday,
            [Wednesday.Value] = Wednesday,
            [Thursday.Value] = Thursday,
            [Friday.Value] = Friday,
            [Saturday.Value] = Saturday,
            [Sunday.Value] = Sunday
        };

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<global::MyApp.Domain.DayOfWeek> All => s_all;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<string> Names => s_names;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<int> Values => s_values;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static int Count => s_all.Length;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::MyApp.Domain.DayOfWeek FromName(string name)
    {
        if (!s_byName.TryGetValue(name, out var result))
            throw new global::System.Collections.Generic.KeyNotFoundException(
                $"'{name}' is not a valid name for DayOfWeek");

        return result;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool TryFromName(string name, out global::MyApp.Domain.DayOfWeek? result) =>
        s_byName.TryGetValue(name, out result);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::MyApp.Domain.DayOfWeek FromValue(int value)
    {
        if (!s_byValue.TryGetValue(value, out var result))
            throw new global::System.Collections.Generic.KeyNotFoundException(
                $"'{value}' is not a valid value for DayOfWeek");

        return result;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool TryFromValue(int value, out global::MyApp.Domain.DayOfWeek? result) =>
        s_byValue.TryGetValue(value, out result);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool ContainsName(string name) => s_byName.ContainsKey(name);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool ContainsValue(int value) => s_byValue.ContainsKey(value);
}
