//HintName: Priority.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
partial class Priority
{
    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<global::Priority> s_all =
        global::System.Array.AsReadOnly(new global::Priority[]
        {
            Low,
            Medium,
            High
        });

    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<string> s_names =
        global::System.Array.AsReadOnly(new string[]
        {
            Low.Name,
            Medium.Name,
            High.Name
        });

    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<int> s_values =
        global::System.Array.AsReadOnly(new int[]
        {
            Low.Value,
            Medium.Value,
            High.Value
        });

    private static readonly global::System.Collections.Generic.Dictionary<string, global::Priority> s_byName =
        new global::System.Collections.Generic.Dictionary<string, global::Priority>(3, global::System.StringComparer.Ordinal)
        {
            [Low.Name] = Low,
            [Medium.Name] = Medium,
            [High.Name] = High
        };

    private static readonly global::System.Collections.Generic.Dictionary<int, global::Priority> s_byValue =
        new global::System.Collections.Generic.Dictionary<int, global::Priority>(3)
        {
            [Low.Value] = Low,
            [Medium.Value] = Medium,
            [High.Value] = High
        };

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<global::Priority> All => s_all;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<string> Names => s_names;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<int> Values => s_values;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public const int Count = 3;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::Priority FromName(string name)
    {
        if (!s_byName.TryGetValue(name, out var result))
            throw new global::System.Collections.Generic.KeyNotFoundException(
                $"'{name}' is not a valid name for Priority");

        return result;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool TryFromName(string name, out global::Priority? result) =>
        s_byName.TryGetValue(name, out result);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::Priority FromValue(int value)
    {
        if (!s_byValue.TryGetValue(value, out var result))
            throw new global::System.Collections.Generic.KeyNotFoundException(
                $"'{value}' is not a valid value for Priority");

        return result;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool TryFromValue(int value, out global::Priority? result) =>
        s_byValue.TryGetValue(value, out result);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool ContainsName(string name) => s_byName.ContainsKey(name);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool ContainsValue(int value) => s_byValue.ContainsKey(value);
}
