//HintName: MyApp.Domain.Color.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyApp.Domain;

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
partial class Color
{
    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<global::MyApp.Domain.Color> s_all =
        global::System.Array.AsReadOnly(new global::MyApp.Domain.Color[]
        {
            Red,
            Green,
            Blue
        });

    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<string> s_names =
        global::System.Array.AsReadOnly(new string[]
        {
            Red.Name,
            Green.Name,
            Blue.Name
        });

    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<string> s_values =
        global::System.Array.AsReadOnly(new string[]
        {
            Red.Value,
            Green.Value,
            Blue.Value
        });

    private static readonly global::System.Collections.Generic.Dictionary<string, global::MyApp.Domain.Color> s_byName =
        new global::System.Collections.Generic.Dictionary<string, global::MyApp.Domain.Color>(3, global::System.StringComparer.Ordinal)
        {
            [Red.Name] = Red,
            [Green.Name] = Green,
            [Blue.Name] = Blue
        };

    private static readonly global::System.Collections.Generic.Dictionary<string, global::MyApp.Domain.Color> s_byValue =
        new global::System.Collections.Generic.Dictionary<string, global::MyApp.Domain.Color>(3)
        {
            [Red.Value] = Red,
            [Green.Value] = Green,
            [Blue.Value] = Blue
        };

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<global::MyApp.Domain.Color> All => s_all;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<string> Names => s_names;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<string> Values => s_values;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public const int Count = 3;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::MyApp.Domain.Color FromName(string name)
    {
        if (!s_byName.TryGetValue(name, out var result))
            throw new global::System.Collections.Generic.KeyNotFoundException(
                $"'{name}' is not a valid name for Color");

        return result;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool TryFromName(string name, out global::MyApp.Domain.Color? result) =>
        s_byName.TryGetValue(name, out result);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::MyApp.Domain.Color FromValue(string value)
    {
        if (!s_byValue.TryGetValue(value, out var result))
            throw new global::System.Collections.Generic.KeyNotFoundException(
                $"'{value}' is not a valid value for Color");

        return result;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool TryFromValue(string value, out global::MyApp.Domain.Color? result) =>
        s_byValue.TryGetValue(value, out result);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool ContainsName(string name) => s_byName.ContainsKey(name);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool ContainsValue(string value) => s_byValue.ContainsKey(value);
}
