//HintName: OrderStatus.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyApp.Domain;

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
partial class OrderStatus
{
    private static readonly global::MyApp.Domain.OrderStatus[] s_all = new global::MyApp.Domain.OrderStatus[]
    {
        Pending,
        Paid,
        Shipped
    };

    private static readonly string[] s_names = new string[]
    {
        Pending.Name,
        Paid.Name,
        Shipped.Name
    };

    private static readonly int[] s_values = new int[]
    {
        Pending.Value,
        Paid.Value,
        Shipped.Value
    };

    private static readonly global::System.Collections.Generic.Dictionary<string, global::MyApp.Domain.OrderStatus> s_byName =
        new global::System.Collections.Generic.Dictionary<string, global::MyApp.Domain.OrderStatus>(global::System.StringComparer.Ordinal)
        {
            [Pending.Name] = Pending,
            [Paid.Name] = Paid,
            [Shipped.Name] = Shipped
        };

    private static readonly global::System.Collections.Generic.Dictionary<int, global::MyApp.Domain.OrderStatus> s_byValue =
        new global::System.Collections.Generic.Dictionary<int, global::MyApp.Domain.OrderStatus>()
        {
            [Pending.Value] = Pending,
            [Paid.Value] = Paid,
            [Shipped.Value] = Shipped
        };

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<global::MyApp.Domain.OrderStatus> All => s_all;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<string> Names => s_names;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::System.Collections.Generic.IReadOnlyList<int> Values => s_values;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static int Count => s_all.Length;

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::MyApp.Domain.OrderStatus FromName(string name)
    {
        if (!s_byName.TryGetValue(name, out var result))
            throw new global::System.Collections.Generic.KeyNotFoundException(
                $"'{name}' is not a valid name for OrderStatus");

        return result;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool TryFromName(string name, out global::MyApp.Domain.OrderStatus? result) =>
        s_byName.TryGetValue(name, out result);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static global::MyApp.Domain.OrderStatus FromValue(int value)
    {
        if (!s_byValue.TryGetValue(value, out var result))
            throw new global::System.Collections.Generic.KeyNotFoundException(
                $"'{value}' is not a valid value for OrderStatus");

        return result;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool TryFromValue(int value, out global::MyApp.Domain.OrderStatus? result) =>
        s_byValue.TryGetValue(value, out result);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool ContainsName(string name) => s_byName.ContainsKey(name);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.Generator", "REPLACED")]
    public static bool ContainsValue(int value) => s_byValue.ContainsKey(value);
}
