//HintName: MyApp.Domain.OrderStatus.SystemTextJson.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyApp.Domain;

[global::System.Text.Json.Serialization.JsonConverter(typeof(OrderStatusValueJsonConverter))]
partial class OrderStatus { }

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.SystemTextJson.Generator", "REPLACED")]
internal sealed class OrderStatusValueJsonConverter
    : global::System.Text.Json.Serialization.JsonConverter<global::MyApp.Domain.OrderStatus>
{
    public override bool HandleNull => true;


    public override global::MyApp.Domain.OrderStatus Read(
        ref global::System.Text.Json.Utf8JsonReader reader,
        global::System.Type typeToConvert,
        global::System.Text.Json.JsonSerializerOptions options)
    {

        var value = global::System.Text.Json.JsonSerializer.Deserialize<int>(ref reader, options);

        if (!global::MyApp.Domain.OrderStatus.TryFromValue(value, out var result))
            throw new global::System.Text.Json.JsonException(
                $"'{value}' is not a valid value for OrderStatus.");

        return result!;
    }

    public override void Write(
        global::System.Text.Json.Utf8JsonWriter writer,
        global::MyApp.Domain.OrderStatus value,
        global::System.Text.Json.JsonSerializerOptions options)
        => global::System.Text.Json.JsonSerializer.Serialize(writer, value.Value, options);
}
