//HintName: Priority.SystemTextJson.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

[global::System.Text.Json.Serialization.JsonConverter(typeof(PriorityNameJsonConverter))]
partial class Priority { }

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.SystemTextJson.Generator", "REPLACED")]
internal sealed class PriorityNameJsonConverter
    : global::System.Text.Json.Serialization.JsonConverter<global::Priority>
{

    public override global::Priority Read(
        ref global::System.Text.Json.Utf8JsonReader reader,
        global::System.Type typeToConvert,
        global::System.Text.Json.JsonSerializerOptions options)
    {
        if (reader.TokenType != global::System.Text.Json.JsonTokenType.String)
            throw new global::System.Text.Json.JsonException(
                $"Expected a JSON string for Priority but got {reader.TokenType}.");

        var name = reader.GetString()!;

        if (!global::Priority.TryFromName(name, out var result))
            throw new global::System.Text.Json.JsonException(
                $"'{name}' is not a valid name for Priority.");

        return result!;
    }

    public override void Write(
        global::System.Text.Json.Utf8JsonWriter writer,
        global::Priority value,
        global::System.Text.Json.JsonSerializerOptions options)
        => writer.WriteStringValue(value.Name);
}
