//HintName: OptimizedEnumJsonConverterAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace LayeredCraft.OptimizedEnums.SystemTextJson
{
    /// <summary>
    /// Controls how an OptimizedEnum is serialized to and deserialized from JSON.
    /// </summary>
    public enum OptimizedEnumJsonConverterType
    {
        /// <summary>Serialize as the member's Name string (e.g. "Pending").</summary>
        ByName = 0,

        /// <summary>Serialize as the member's underlying Value (e.g. 1).</summary>
        ByValue = 1,
    }

    /// <summary>
    /// Instructs the OptimizedEnums source generator to emit a System.Text.Json converter
    /// for the decorated OptimizedEnum class and stamp it with [JsonConverter] automatically.
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class,
        AllowMultiple = false,
        Inherited = false)]
    public sealed class OptimizedEnumJsonConverterAttribute : global::System.Attribute
    {
        /// <summary>Initializes a new instance.</summary>
        public OptimizedEnumJsonConverterAttribute(OptimizedEnumJsonConverterType converterType)
        {
            ConverterType = converterType;
        }

        /// <summary>Gets the serialization strategy for this converter.</summary>
        public OptimizedEnumJsonConverterType ConverterType { get; }
    }
}
