//HintName: MyApp.Domain.OrderStatus.SystemTextJson.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyApp.Domain;

[global::System.Text.Json.Serialization.JsonConverter(typeof(OrderStatusNameJsonConverter))]
partial class OrderStatus { }

[global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.OptimizedEnums.SystemTextJson.Generator", "REPLACED")]
internal sealed class OrderStatusNameJsonConverter
    : global::System.Text.Json.Serialization.JsonConverter<global::MyApp.Domain.OrderStatus>
{
    public override bool HandleNull => true;


    public override global::MyApp.Domain.OrderStatus Read(
        ref global::System.Text.Json.Utf8JsonReader reader,
        global::System.Type typeToConvert,
        global::System.Text.Json.JsonSerializerOptions options)
    {
        if (reader.TokenType != global::System.Text.Json.JsonTokenType.String)
            throw new global::System.Text.Json.JsonException(
                $"Expected a JSON string for OrderStatus but got {reader.TokenType}.");

        var name = reader.GetString()!;

        if (!global::MyApp.Domain.OrderStatus.TryFromName(name, out var result))
            throw new global::System.Text.Json.JsonException(
                $"'{name}' is not a valid name for OrderStatus.");

        return result!;
    }

    public override void Write(
        global::System.Text.Json.Utf8JsonWriter writer,
        global::MyApp.Domain.OrderStatus value,
        global::System.Text.Json.JsonSerializerOptions options)
        => writer.WriteStringValue(value.Name);
}
